import { Oswald} from "next/font/google";
import "@/app/globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";

const oswald = Oswald({
  variable: "--font-oswald-ilatic",
  subsets: ["latin"],
});



export const metadata = {
  title: "SchoolFlow | Organize para melhor aprender!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${oswald.variable}  h-full antialiased`}

      >
      
      <body className="min-h-full flex flex-col">
        
        {children}
        </body>
    </html>
  );
}
