import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import TopBar from "@/components/topBar.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SchoolFlow | Organize para melhor aprender!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <TopBar/>
        {children}
        </body>
    </html>
  );
}
